---
# tasks file for roles/nginx-ssl-selfsigned

- name: system packages | install openssl | redhat
  become: yes
  yum:
    name: openssl
    state: present
  when: ansible_os_family == 'RedHat'

- name: system packages | install openssl | ubuntu
  become: yes
  apt:
    name: openssl
    state: present
  when: ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'

- name: nginx | create certificates directory
  become: yes
  file:
    path: "{{ item | dirname }}"
    state: directory
  with_items:
    - "{{ nginx_ssl_certificate }}"
    - "{{ nginx_ssl_certificate_key }}"

# http://serialized.net/2013/04/simply-generating-self-signed-ssl-certs-with-ansible/
- name: nginx | generate self-signed SSL certificate
  become: yes
  command:
    openssl req -new -nodes -x509 -subj "{{ nginx_ssl_certificate_subject }}" -days {{ nginx_ssl_certificate_days }} -keyout {{ nginx_ssl_certificate_key }} -out {{ nginx_ssl_certificate }} -extensions v3_ca
  args:
    creates: "{{ nginx_ssl_certificate }}"
